spring.application.name=FYDP Sync

server.port=9090

#database
spring.datasource.url=jdbc:mysql://localhost:3306/fydp
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#thymeleaf
spring.thymeleaf.cache=false
